// Generated by scripts/render-logo.swift. Do not edit by hand.
// The menu bar glyph as PNG data, so the executable needs no resource bundle to show its icon.
enum MenuBarGlyphData {
    /// 18 x 18 pixels, for a 1x display.
    static let png1x = """
        iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAAB
        AAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAEqADAAQAAAABAAAAEgAAAACaqbJVAAABzklEQVQ4EY3UzytmURzH
        cb/zY0LRxGLUNIrBhhVDSdPMlKxGmjJWYjElbFhY21lZ8QcodmrKZsxEGU0KyyErFrKiZphGmYb3++mep/u4xKdenXPPufd7
        77n3PE9uVjJvGZpBF2pRhn/4jUengDN/4TOG8RXXkT+0u2jFg2nkjD3koAf5OIbFvuMNPqAUGfGCeOo5OIPj/bjCCcxHVOAH
        vElGbhd6yWwbRvApOrOdtglHeIL/aMYg7s0CM+GdLNKvwjeMwWV2YxyXuEAd7swOo3/xBUN4DQvPoyHqhxvZziKRbEbO0YJC
        eKxnkRe0S3Bpodgo/URqGPE9mC24hybhcp/DZfi1phEKuecScdC7dUYz1bQn8KJX8AP04T1CIZ82EV+oJ7iLd+FODhcs0y9B
        OdbhuC/bpaeSFzq07iEzgFN47HawdTe7v7zQr2f2YcFU4oW8yFhoDZ64gkO4ZJ/Goi5tAs6nEy/kSd7Bz/wOYe6S/gG80J+P
        P2JjP5EiRiyyEc34+D6hd5/CTzgf18txOvG7bjPaAbeAd5NPsQmLhqXTTSXjidJvnSm/ikvyHyC86Dr6xbgdv2gl/FGnEi8U
        xuKt827UUNj2KeawinRuAIBDaoLV941UAAAAAElFTkSuQmCC
        """

    /// 36 x 36 pixels, for a 2x display.
    static let png2x = """
        iVBORw0KGgoAAAANSUhEUgAAACQAAAAkCAYAAADhAJiYAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAAB
        AAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAJKADAAQAAAABAAAAJAAAAAAqDuP8AAAEZklEQVRYCbWXW4hWVRSA
        K9PuWVppZkFlTYbRnaKihm4gBPbSQ1JB9GAIQUSEdoGKKIgEsTsVDfVSQRD5EBQmCj3UQ0JheekCZTmUFV5Ky27f5+xla/ac
        M/8ZtQXfrLXXXnudfVlnn3/G7ddNJhJ2A1wCR8NO2AL7XPbvkLGPmBUwpYrdRnstfF5YU/QXaCf8v8nHZP6n8Ct6OXwAvxdf
        9IV2Mk7uLXgMpsM+k6lkige9ie1xhfggJxb9bXolMeNiUC/d68iuJMEycMVnwx+QZRKN9aDO8huNAVgNJ8ImWAR7LfPJ4MoX
        lkwT0G/Di6Wt0s67M0j7dDuSuLPnpHareUBrz1DHzNL/U9HHoq+DWyGO4cfSF+oejHWlMQ3tKfwC2yEfOc2xy3sMcfV5Ry6j
        fUdK9UqJiV2Kh84t/idS7PPJ3iNzQ0lq7VzUksEdsE6uhXkpZgm2k7w/+TZi55jU1ds8gpBYtdpX/kG4AA6BLnJQCnJB5rHg
        z0z+zuaFROYJZfu2ksUaWQyu+go4CprEHfRNjRyfYB/cFDia7+aUIBKFvrQMnF3FRG0dg/8leAhehq0QY0M/jW9M8ijRMbjW
        k0umu6qYa4q/v/LX46M9q8TvVgfutkYaZyTXauxX4Wfw9o5roA87i981JY8d8jT/NV9nMbkreR3aJq7fSV0P3j8hvuqxC216
        cwR30T7IV30LHFkG+MbMgPGl3UudRMDd4NvZNKkPeyXI/W65Sd5NzneK787i8wK0zix+38jDoUmuwvk31JMaaApu83kEJng/
        BQxgu2Nxh/Rj54fcS1s5DJ6Eq20UcWE5VntBdHbRfkwdtAOOTwPyt8/XNj/klhLnhPV7AYYswsix2nOiM2trpUniLbFuLGoH
        +4F065Ub4fZd1n9/vPyUtfAcfGujyAlhJL0m2T3Nj4jIK9pE+wV4HFZWfRH3FX6Pq5aTcWyHiFP7wrRtBl0jxVrJCbraKxh3
        akp3Mfa6hlyfpZhhZtMs3V4/rCH+TH0GpsNM8Dil6bt1Of718DVMAMc0SVygI/qaJhT1E8EPYCyPRtJTsWOCWTuJU1Jck9la
        P00TMnmW+TS+gy/hr9QxiC31ZL2PXJSY6yyYDflZrTtE3Ah5Ck9TzezA/ym8AQ/DXDgXDoVech8BOae/qRolzzoC6h0Kv1fA
        rEL41D7oG3DVHoWE/QO2Utdb65ENhQ//6/HEanw9l4KF7Rc+/F21Y+q3LN9PdA+Xeof8kE5LIR7NI6l9HLY7GPUR2kvR39a1
        TMIhWcZUP15iefV+k7qIF+JNkMe22UtGS1ivyh3bCP4EDfFesZijLtR+HrZBLf7gin+D6r5o+9Y+G41a10f2JwHz4DUYX4JP
        Q0sWV78BooCtk/Og12QI2TVGPSY5n+jFsAy+h7bt3xP/FPK1Sn1kbYET6bCAo4hDeyPXu9yWQ/8qcCdbpeuE2hJ4rB5nTDB0
        H776F+Qgvn6w/lplbyfUlti8ftOc4AzYCkthM4wq/wL4MXBiWho9awAAAABJRU5ErkJggg==
        """
}
